using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace OneJS {
    /// <summary>
    /// Generates TypeScript definition files for cartridge objects.
    /// Enables intellisense for __cart('slug') access.
    /// </summary>
    public static class CartridgeTypeGenerator {
        // Common Unity type mappings
        static readonly Dictionary<Type, string> TypeMap = new Dictionary<Type, string> {
            // Primitives
            { typeof(int), "number" },
            { typeof(float), "number" },
            { typeof(double), "number" },
            { typeof(long), "number" },
            { typeof(short), "number" },
            { typeof(byte), "number" },
            { typeof(bool), "boolean" },
            { typeof(string), "string" },

            // Common Unity types - map to CS namespace
            { typeof(Texture2D), "CS.UnityEngine.Texture2D" },
            { typeof(Texture), "CS.UnityEngine.Texture" },
            { typeof(Sprite), "CS.UnityEngine.Sprite" },
            { typeof(Material), "CS.UnityEngine.Material" },
            { typeof(AudioClip), "CS.UnityEngine.AudioClip" },
            { typeof(GameObject), "CS.UnityEngine.GameObject" },
            { typeof(Transform), "CS.UnityEngine.Transform" },
            { typeof(Color), "CS.UnityEngine.Color" },
            { typeof(Color32), "CS.UnityEngine.Color32" },
            { typeof(Vector2), "CS.UnityEngine.Vector2" },
            { typeof(Vector3), "CS.UnityEngine.Vector3" },
            { typeof(Vector4), "CS.UnityEngine.Vector4" },
            { typeof(Quaternion), "CS.UnityEngine.Quaternion" },
            { typeof(Rect), "CS.UnityEngine.Rect" },
            { typeof(Bounds), "CS.UnityEngine.Bounds" },
            { typeof(AnimationCurve), "CS.UnityEngine.AnimationCurve" },
            { typeof(Gradient), "CS.UnityEngine.Gradient" },
            { typeof(ScriptableObject), "CS.UnityEngine.ScriptableObject" },
        };

        /// <summary>
        /// Generate TypeScript definitions for a cartridge's global objects.
        /// </summary>
        public static string Generate(UICartridge cartridge) {
            if (cartridge == null) return "// Error: null cartridge\nexport {};";

            var sb = new StringBuilder();

            sb.AppendLine($"// Auto-generated by OneJS Cartridge: {cartridge.Slug}");
            sb.AppendLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            if (cartridge.Objects == null || cartridge.Objects.Count == 0) {
                sb.AppendLine("// No global objects defined in this cartridge");
                sb.AppendLine("export {};");
                return sb.ToString();
            }

            // Generate interface and __cart overload for this cartridge
            var path = cartridge.RelativePath;
            var interfaceName = ToPascalCase(cartridge.Slug) + "Cartridge";

            sb.AppendLine("declare global {");
            sb.AppendLine($"    interface {interfaceName} {{");

            foreach (var entry in cartridge.Objects) {
                if (string.IsNullOrEmpty(entry.key) || entry.value == null) continue;

                var tsType = GetTypeScriptType(entry.value.GetType());
                sb.AppendLine($"        {entry.key}: {tsType};");
            }

            sb.AppendLine("    }");
            sb.AppendLine($"    function __cart(path: '{path}'): {interfaceName};");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("export {};");

            return sb.ToString();
        }

        /// <summary>
        /// Map a C# type to its TypeScript equivalent.
        /// </summary>
        static string GetTypeScriptType(Type type) {
            if (type == null) return "any";

            // Check exact match first
            if (TypeMap.TryGetValue(type, out var mapped)) {
                return mapped;
            }

            // Check for ScriptableObject subclasses
            if (typeof(ScriptableObject).IsAssignableFrom(type)) {
                return GetFullTypeName(type);
            }

            // Check for Component subclasses
            if (typeof(Component).IsAssignableFrom(type)) {
                return GetFullTypeName(type);
            }

            // Check for UnityEngine.Object subclasses
            if (typeof(UnityEngine.Object).IsAssignableFrom(type)) {
                return GetFullTypeName(type);
            }

            // Fallback for unknown types
            return "any";
        }

        /// <summary>
        /// Get the full TypeScript type name with CS prefix.
        /// </summary>
        static string GetFullTypeName(Type type) {
            var fullName = type.FullName;
            if (string.IsNullOrEmpty(fullName)) return "any";

            // Handle nested types (replace + with .)
            fullName = fullName.Replace("+", ".");

            return $"CS.{fullName}";
        }

        /// <summary>
        /// Convert a kebab-case slug to PascalCase for interface names.
        /// </summary>
        static string ToPascalCase(string slug) {
            if (string.IsNullOrEmpty(slug)) return slug;

            var sb = new StringBuilder();
            var capitalizeNext = true;

            foreach (var c in slug) {
                if (c == '-' || c == '_') {
                    capitalizeNext = true;
                } else if (capitalizeNext) {
                    sb.Append(char.ToUpperInvariant(c));
                    capitalizeNext = false;
                } else {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}
